name: Daily PDF Scraper
on:
  schedule:
    - cron: "0 3 * * *"  # প্ৰতিদিন 3 AM UTC (ভাৰতত 8:30 AM)
  workflow_dispatch:    # মেনুৱেলি চালাব পাৰে

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Run Scraper
        env:
          DRIVE_API_JSON: ${{ secrets.DRIVE_API_JSON }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        run: python bot/scraper.py
        
      - name: Update Database
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data/
          git commit -m "Auto-update PDF metadata"
          git push
